// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.3
// source: casbin_rule/v1/casbin_rule.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CasbinRule_GetAllSubjects_FullMethodName = "/api.casbin_rule.v1.CasbinRule/GetAllSubjects"
)

// CasbinRuleClient is the client API for CasbinRule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CasbinRuleClient interface {
	// 获取所有鉴权主体
	GetAllSubjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllSubjectsRpl, error)
}

type casbinRuleClient struct {
	cc grpc.ClientConnInterface
}

func NewCasbinRuleClient(cc grpc.ClientConnInterface) CasbinRuleClient {
	return &casbinRuleClient{cc}
}

func (c *casbinRuleClient) GetAllSubjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllSubjectsRpl, error) {
	out := new(GetAllSubjectsRpl)
	err := c.cc.Invoke(ctx, CasbinRule_GetAllSubjects_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasbinRuleServer is the server API for CasbinRule service.
// All implementations must embed UnimplementedCasbinRuleServer
// for forward compatibility
type CasbinRuleServer interface {
	// 获取所有鉴权主体
	GetAllSubjects(context.Context, *emptypb.Empty) (*GetAllSubjectsRpl, error)
	mustEmbedUnimplementedCasbinRuleServer()
}

// UnimplementedCasbinRuleServer must be embedded to have forward compatible implementations.
type UnimplementedCasbinRuleServer struct {
}

func (UnimplementedCasbinRuleServer) GetAllSubjects(context.Context, *emptypb.Empty) (*GetAllSubjectsRpl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSubjects not implemented")
}
func (UnimplementedCasbinRuleServer) mustEmbedUnimplementedCasbinRuleServer() {}

// UnsafeCasbinRuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CasbinRuleServer will
// result in compilation errors.
type UnsafeCasbinRuleServer interface {
	mustEmbedUnimplementedCasbinRuleServer()
}

func RegisterCasbinRuleServer(s grpc.ServiceRegistrar, srv CasbinRuleServer) {
	s.RegisterService(&CasbinRule_ServiceDesc, srv)
}

func _CasbinRule_GetAllSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinRuleServer).GetAllSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CasbinRule_GetAllSubjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinRuleServer).GetAllSubjects(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CasbinRule_ServiceDesc is the grpc.ServiceDesc for CasbinRule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CasbinRule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.casbin_rule.v1.CasbinRule",
	HandlerType: (*CasbinRuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSubjects",
			Handler:    _CasbinRule_GetAllSubjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "casbin_rule/v1/casbin_rule.proto",
}
