// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: role/v1/role.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddDomainRoleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddDomainRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddDomainRoleReqMultiError, or nil if none found.
func (m *AddDomainRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddDomainRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_AddDomainRoleReq_DomainName_Pattern.MatchString(m.GetDomainName()) {
		err := AddDomainRoleReqValidationError{
			field:  "DomainName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_AddDomainRoleReq_RoleName_Pattern.MatchString(m.GetRoleName()) {
		err := AddDomainRoleReqValidationError{
			field:  "RoleName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddDomainRoleReqMultiError(errors)
	}

	return nil
}

// AddDomainRoleReqMultiError is an error wrapping multiple validation errors
// returned by AddDomainRoleReq.ValidateAll() if the designated constraints
// aren't met.
type AddDomainRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddDomainRoleReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddDomainRoleReqMultiError) AllErrors() []error { return m }

// AddDomainRoleReqValidationError is the validation error returned by
// AddDomainRoleReq.Validate if the designated constraints aren't met.
type AddDomainRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddDomainRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddDomainRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddDomainRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddDomainRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddDomainRoleReqValidationError) ErrorName() string { return "AddDomainRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e AddDomainRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddDomainRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddDomainRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddDomainRoleReqValidationError{}

var _AddDomainRoleReq_DomainName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

var _AddDomainRoleReq_RoleName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

// Validate checks the field values on AddDomainRoleRpl with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddDomainRoleRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddDomainRoleRplMultiError, or nil if none found.
func (m *AddDomainRoleRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *AddDomainRoleRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddDomainRoleRplValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddDomainRoleRplMultiError(errors)
	}

	return nil
}

// AddDomainRoleRplMultiError is an error wrapping multiple validation errors
// returned by AddDomainRoleRpl.ValidateAll() if the designated constraints
// aren't met.
type AddDomainRoleRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddDomainRoleRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddDomainRoleRplMultiError) AllErrors() []error { return m }

// AddDomainRoleRplValidationError is the validation error returned by
// AddDomainRoleRpl.Validate if the designated constraints aren't met.
type AddDomainRoleRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddDomainRoleRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddDomainRoleRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddDomainRoleRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddDomainRoleRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddDomainRoleRplValidationError) ErrorName() string { return "AddDomainRoleRplValidationError" }

// Error satisfies the builtin error interface
func (e AddDomainRoleRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddDomainRoleRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddDomainRoleRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddDomainRoleRplValidationError{}

// Validate checks the field values on UpdateDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDomainRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDomainRoleReqMultiError, or nil if none found.
func (m *UpdateDomainRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDomainRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_UpdateDomainRoleReq_DomainName_Pattern.MatchString(m.GetDomainName()) {
		err := UpdateDomainRoleReqValidationError{
			field:  "DomainName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UpdateDomainRoleReq_RoleName_Pattern.MatchString(m.GetRoleName()) {
		err := UpdateDomainRoleReqValidationError{
			field:  "RoleName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UpdateDomainRoleReq_NewRoleName_Pattern.MatchString(m.GetNewRoleName()) {
		err := UpdateDomainRoleReqValidationError{
			field:  "NewRoleName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateDomainRoleReqMultiError(errors)
	}

	return nil
}

// UpdateDomainRoleReqMultiError is an error wrapping multiple validation
// errors returned by UpdateDomainRoleReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateDomainRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDomainRoleReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDomainRoleReqMultiError) AllErrors() []error { return m }

// UpdateDomainRoleReqValidationError is the validation error returned by
// UpdateDomainRoleReq.Validate if the designated constraints aren't met.
type UpdateDomainRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDomainRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDomainRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDomainRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDomainRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDomainRoleReqValidationError) ErrorName() string {
	return "UpdateDomainRoleReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDomainRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDomainRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDomainRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDomainRoleReqValidationError{}

var _UpdateDomainRoleReq_DomainName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

var _UpdateDomainRoleReq_RoleName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

var _UpdateDomainRoleReq_NewRoleName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

// Validate checks the field values on UpdateDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDomainRoleRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDomainRoleRplMultiError, or nil if none found.
func (m *UpdateDomainRoleRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDomainRoleRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateDomainRoleRplValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateDomainRoleRplMultiError(errors)
	}

	return nil
}

// UpdateDomainRoleRplMultiError is an error wrapping multiple validation
// errors returned by UpdateDomainRoleRpl.ValidateAll() if the designated
// constraints aren't met.
type UpdateDomainRoleRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDomainRoleRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDomainRoleRplMultiError) AllErrors() []error { return m }

// UpdateDomainRoleRplValidationError is the validation error returned by
// UpdateDomainRoleRpl.Validate if the designated constraints aren't met.
type UpdateDomainRoleRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDomainRoleRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDomainRoleRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDomainRoleRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDomainRoleRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDomainRoleRplValidationError) ErrorName() string {
	return "UpdateDomainRoleRplValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDomainRoleRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDomainRoleRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDomainRoleRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDomainRoleRplValidationError{}

// Validate checks the field values on DeleteDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDomainRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDomainRoleReqMultiError, or nil if none found.
func (m *DeleteDomainRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDomainRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_DeleteDomainRoleReq_DomainName_Pattern.MatchString(m.GetDomainName()) {
		err := DeleteDomainRoleReqValidationError{
			field:  "DomainName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_DeleteDomainRoleReq_RoleName_Pattern.MatchString(m.GetRoleName()) {
		err := DeleteDomainRoleReqValidationError{
			field:  "RoleName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteDomainRoleReqMultiError(errors)
	}

	return nil
}

// DeleteDomainRoleReqMultiError is an error wrapping multiple validation
// errors returned by DeleteDomainRoleReq.ValidateAll() if the designated
// constraints aren't met.
type DeleteDomainRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDomainRoleReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDomainRoleReqMultiError) AllErrors() []error { return m }

// DeleteDomainRoleReqValidationError is the validation error returned by
// DeleteDomainRoleReq.Validate if the designated constraints aren't met.
type DeleteDomainRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDomainRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDomainRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDomainRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDomainRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDomainRoleReqValidationError) ErrorName() string {
	return "DeleteDomainRoleReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDomainRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDomainRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDomainRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDomainRoleReqValidationError{}

var _DeleteDomainRoleReq_DomainName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

var _DeleteDomainRoleReq_RoleName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

// Validate checks the field values on DeleteDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDomainRoleRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDomainRoleRplMultiError, or nil if none found.
func (m *DeleteDomainRoleRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDomainRoleRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteDomainRoleRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteDomainRoleRplValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteDomainRoleRplMultiError(errors)
	}

	return nil
}

// DeleteDomainRoleRplMultiError is an error wrapping multiple validation
// errors returned by DeleteDomainRoleRpl.ValidateAll() if the designated
// constraints aren't met.
type DeleteDomainRoleRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDomainRoleRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDomainRoleRplMultiError) AllErrors() []error { return m }

// DeleteDomainRoleRplValidationError is the validation error returned by
// DeleteDomainRoleRpl.Validate if the designated constraints aren't met.
type DeleteDomainRoleRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDomainRoleRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDomainRoleRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDomainRoleRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDomainRoleRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDomainRoleRplValidationError) ErrorName() string {
	return "DeleteDomainRoleRplValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDomainRoleRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDomainRoleRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDomainRoleRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDomainRoleRplValidationError{}

// Validate checks the field values on GetAllDomainsRpl with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAllDomainsRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllDomainsRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllDomainsRplMultiError, or nil if none found.
func (m *GetAllDomainsRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllDomainsRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAllDomainsRplValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAllDomainsRplValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAllDomainsRplValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAllDomainsRplMultiError(errors)
	}

	return nil
}

// GetAllDomainsRplMultiError is an error wrapping multiple validation errors
// returned by GetAllDomainsRpl.ValidateAll() if the designated constraints
// aren't met.
type GetAllDomainsRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllDomainsRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllDomainsRplMultiError) AllErrors() []error { return m }

// GetAllDomainsRplValidationError is the validation error returned by
// GetAllDomainsRpl.Validate if the designated constraints aren't met.
type GetAllDomainsRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllDomainsRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllDomainsRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllDomainsRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllDomainsRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllDomainsRplValidationError) ErrorName() string { return "GetAllDomainsRplValidationError" }

// Error satisfies the builtin error interface
func (e GetAllDomainsRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllDomainsRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllDomainsRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllDomainsRplValidationError{}

// Validate checks the field values on GetDomainRolesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDomainRolesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDomainRolesReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDomainRolesReqMultiError, or nil if none found.
func (m *GetDomainRolesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDomainRolesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_GetDomainRolesReq_DomainName_Pattern.MatchString(m.GetDomainName()) {
		err := GetDomainRolesReqValidationError{
			field:  "DomainName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for RoleName

	if m.GetPageSize() <= 0 {
		err := GetDomainRolesReqValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageNum() <= 0 {
		err := GetDomainRolesReqValidationError{
			field:  "PageNum",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDomainRolesReqMultiError(errors)
	}

	return nil
}

// GetDomainRolesReqMultiError is an error wrapping multiple validation errors
// returned by GetDomainRolesReq.ValidateAll() if the designated constraints
// aren't met.
type GetDomainRolesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDomainRolesReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDomainRolesReqMultiError) AllErrors() []error { return m }

// GetDomainRolesReqValidationError is the validation error returned by
// GetDomainRolesReq.Validate if the designated constraints aren't met.
type GetDomainRolesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDomainRolesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDomainRolesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDomainRolesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDomainRolesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDomainRolesReqValidationError) ErrorName() string {
	return "GetDomainRolesReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetDomainRolesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDomainRolesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDomainRolesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDomainRolesReqValidationError{}

var _GetDomainRolesReq_DomainName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

// Validate checks the field values on GetDomainRolesRpl with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDomainRolesRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDomainRolesRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDomainRolesRplMultiError, or nil if none found.
func (m *GetDomainRolesRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDomainRolesRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDomainRolesRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDomainRolesRplValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDomainRolesRplValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDomainRolesRplMultiError(errors)
	}

	return nil
}

// GetDomainRolesRplMultiError is an error wrapping multiple validation errors
// returned by GetDomainRolesRpl.ValidateAll() if the designated constraints
// aren't met.
type GetDomainRolesRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDomainRolesRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDomainRolesRplMultiError) AllErrors() []error { return m }

// GetDomainRolesRplValidationError is the validation error returned by
// GetDomainRolesRpl.Validate if the designated constraints aren't met.
type GetDomainRolesRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDomainRolesRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDomainRolesRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDomainRolesRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDomainRolesRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDomainRolesRplValidationError) ErrorName() string {
	return "GetDomainRolesRplValidationError"
}

// Error satisfies the builtin error interface
func (e GetDomainRolesRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDomainRolesRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDomainRolesRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDomainRolesRplValidationError{}

// Validate checks the field values on AddRoleForSubInDomainReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddRoleForSubInDomainReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddRoleForSubInDomainReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddRoleForSubInDomainReqMultiError, or nil if none found.
func (m *AddRoleForSubInDomainReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddRoleForSubInDomainReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_AddRoleForSubInDomainReq_Sub_Pattern.MatchString(m.GetSub()) {
		err := AddRoleForSubInDomainReqValidationError{
			field:  "Sub",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_AddRoleForSubInDomainReq_Domain_Pattern.MatchString(m.GetDomain()) {
		err := AddRoleForSubInDomainReqValidationError{
			field:  "Domain",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_AddRoleForSubInDomainReq_Role_Pattern.MatchString(m.GetRole()) {
		err := AddRoleForSubInDomainReqValidationError{
			field:  "Role",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddRoleForSubInDomainReqMultiError(errors)
	}

	return nil
}

// AddRoleForSubInDomainReqMultiError is an error wrapping multiple validation
// errors returned by AddRoleForSubInDomainReq.ValidateAll() if the designated
// constraints aren't met.
type AddRoleForSubInDomainReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddRoleForSubInDomainReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddRoleForSubInDomainReqMultiError) AllErrors() []error { return m }

// AddRoleForSubInDomainReqValidationError is the validation error returned by
// AddRoleForSubInDomainReq.Validate if the designated constraints aren't met.
type AddRoleForSubInDomainReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddRoleForSubInDomainReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddRoleForSubInDomainReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddRoleForSubInDomainReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddRoleForSubInDomainReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddRoleForSubInDomainReqValidationError) ErrorName() string {
	return "AddRoleForSubInDomainReqValidationError"
}

// Error satisfies the builtin error interface
func (e AddRoleForSubInDomainReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddRoleForSubInDomainReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddRoleForSubInDomainReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddRoleForSubInDomainReqValidationError{}

var _AddRoleForSubInDomainReq_Sub_Pattern = regexp.MustCompile("^(.*):(.*)$")

var _AddRoleForSubInDomainReq_Domain_Pattern = regexp.MustCompile("^(.*):(.*)$")

var _AddRoleForSubInDomainReq_Role_Pattern = regexp.MustCompile("^(.*):(.*)$")

// Validate checks the field values on AddRoleForSubInDomainRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddRoleForSubInDomainRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddRoleForSubInDomainRpl with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddRoleForSubInDomainRplMultiError, or nil if none found.
func (m *AddRoleForSubInDomainRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *AddRoleForSubInDomainRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return AddRoleForSubInDomainRplMultiError(errors)
	}

	return nil
}

// AddRoleForSubInDomainRplMultiError is an error wrapping multiple validation
// errors returned by AddRoleForSubInDomainRpl.ValidateAll() if the designated
// constraints aren't met.
type AddRoleForSubInDomainRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddRoleForSubInDomainRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddRoleForSubInDomainRplMultiError) AllErrors() []error { return m }

// AddRoleForSubInDomainRplValidationError is the validation error returned by
// AddRoleForSubInDomainRpl.Validate if the designated constraints aren't met.
type AddRoleForSubInDomainRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddRoleForSubInDomainRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddRoleForSubInDomainRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddRoleForSubInDomainRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddRoleForSubInDomainRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddRoleForSubInDomainRplValidationError) ErrorName() string {
	return "AddRoleForSubInDomainRplValidationError"
}

// Error satisfies the builtin error interface
func (e AddRoleForSubInDomainRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddRoleForSubInDomainRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddRoleForSubInDomainRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddRoleForSubInDomainRplValidationError{}

// Validate checks the field values on GetSubsInDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubsInDomainRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubsInDomainRoleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubsInDomainRoleReqMultiError, or nil if none found.
func (m *GetSubsInDomainRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubsInDomainRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDomainName()) < 1 {
		err := GetSubsInDomainRoleReqValidationError{
			field:  "DomainName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRoleName()) < 1 {
		err := GetSubsInDomainRoleReqValidationError{
			field:  "RoleName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSubsInDomainRoleReqMultiError(errors)
	}

	return nil
}

// GetSubsInDomainRoleReqMultiError is an error wrapping multiple validation
// errors returned by GetSubsInDomainRoleReq.ValidateAll() if the designated
// constraints aren't met.
type GetSubsInDomainRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubsInDomainRoleReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubsInDomainRoleReqMultiError) AllErrors() []error { return m }

// GetSubsInDomainRoleReqValidationError is the validation error returned by
// GetSubsInDomainRoleReq.Validate if the designated constraints aren't met.
type GetSubsInDomainRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubsInDomainRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubsInDomainRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubsInDomainRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubsInDomainRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubsInDomainRoleReqValidationError) ErrorName() string {
	return "GetSubsInDomainRoleReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubsInDomainRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubsInDomainRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubsInDomainRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubsInDomainRoleReqValidationError{}

// Validate checks the field values on GetSubsInDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubsInDomainRoleRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubsInDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubsInDomainRoleRplMultiError, or nil if none found.
func (m *GetSubsInDomainRoleRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubsInDomainRoleRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubsInDomainRoleRplValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubsInDomainRoleRplValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubsInDomainRoleRplValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSubsInDomainRoleRplMultiError(errors)
	}

	return nil
}

// GetSubsInDomainRoleRplMultiError is an error wrapping multiple validation
// errors returned by GetSubsInDomainRoleRpl.ValidateAll() if the designated
// constraints aren't met.
type GetSubsInDomainRoleRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubsInDomainRoleRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubsInDomainRoleRplMultiError) AllErrors() []error { return m }

// GetSubsInDomainRoleRplValidationError is the validation error returned by
// GetSubsInDomainRoleRpl.Validate if the designated constraints aren't met.
type GetSubsInDomainRoleRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubsInDomainRoleRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubsInDomainRoleRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubsInDomainRoleRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubsInDomainRoleRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubsInDomainRoleRplValidationError) ErrorName() string {
	return "GetSubsInDomainRoleRplValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubsInDomainRoleRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubsInDomainRoleRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubsInDomainRoleRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubsInDomainRoleRplValidationError{}

// Validate checks the field values on DeleteRoleForSubInDomainReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRoleForSubInDomainReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRoleForSubInDomainReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRoleForSubInDomainReqMultiError, or nil if none found.
func (m *DeleteRoleForSubInDomainReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRoleForSubInDomainReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_DeleteRoleForSubInDomainReq_Sub_Pattern.MatchString(m.GetSub()) {
		err := DeleteRoleForSubInDomainReqValidationError{
			field:  "Sub",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_DeleteRoleForSubInDomainReq_Domain_Pattern.MatchString(m.GetDomain()) {
		err := DeleteRoleForSubInDomainReqValidationError{
			field:  "Domain",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_DeleteRoleForSubInDomainReq_Role_Pattern.MatchString(m.GetRole()) {
		err := DeleteRoleForSubInDomainReqValidationError{
			field:  "Role",
			reason: "value does not match regex pattern \"^(.*):(.*)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteRoleForSubInDomainReqMultiError(errors)
	}

	return nil
}

// DeleteRoleForSubInDomainReqMultiError is an error wrapping multiple
// validation errors returned by DeleteRoleForSubInDomainReq.ValidateAll() if
// the designated constraints aren't met.
type DeleteRoleForSubInDomainReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRoleForSubInDomainReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRoleForSubInDomainReqMultiError) AllErrors() []error { return m }

// DeleteRoleForSubInDomainReqValidationError is the validation error returned
// by DeleteRoleForSubInDomainReq.Validate if the designated constraints
// aren't met.
type DeleteRoleForSubInDomainReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRoleForSubInDomainReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRoleForSubInDomainReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRoleForSubInDomainReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRoleForSubInDomainReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRoleForSubInDomainReqValidationError) ErrorName() string {
	return "DeleteRoleForSubInDomainReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRoleForSubInDomainReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRoleForSubInDomainReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRoleForSubInDomainReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRoleForSubInDomainReqValidationError{}

var _DeleteRoleForSubInDomainReq_Sub_Pattern = regexp.MustCompile("^(.*):(.*)$")

var _DeleteRoleForSubInDomainReq_Domain_Pattern = regexp.MustCompile("^(.*):(.*)$")

var _DeleteRoleForSubInDomainReq_Role_Pattern = regexp.MustCompile("^(.*):(.*)$")

// Validate checks the field values on DeleteRoleForSubInDomainRpl with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRoleForSubInDomainRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRoleForSubInDomainRpl with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRoleForSubInDomainRplMultiError, or nil if none found.
func (m *DeleteRoleForSubInDomainRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRoleForSubInDomainRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return DeleteRoleForSubInDomainRplMultiError(errors)
	}

	return nil
}

// DeleteRoleForSubInDomainRplMultiError is an error wrapping multiple
// validation errors returned by DeleteRoleForSubInDomainRpl.ValidateAll() if
// the designated constraints aren't met.
type DeleteRoleForSubInDomainRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRoleForSubInDomainRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRoleForSubInDomainRplMultiError) AllErrors() []error { return m }

// DeleteRoleForSubInDomainRplValidationError is the validation error returned
// by DeleteRoleForSubInDomainRpl.Validate if the designated constraints
// aren't met.
type DeleteRoleForSubInDomainRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRoleForSubInDomainRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRoleForSubInDomainRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRoleForSubInDomainRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRoleForSubInDomainRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRoleForSubInDomainRplValidationError) ErrorName() string {
	return "DeleteRoleForSubInDomainRplValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRoleForSubInDomainRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRoleForSubInDomainRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRoleForSubInDomainRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRoleForSubInDomainRplValidationError{}

// Validate checks the field values on AddDomainRoleRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddDomainRoleRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddDomainRoleRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddDomainRoleRpl_DataMultiError, or nil if none found.
func (m *AddDomainRoleRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *AddDomainRoleRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatTime

	// no validation rules for Name

	// no validation rules for Domain

	if len(errors) > 0 {
		return AddDomainRoleRpl_DataMultiError(errors)
	}

	return nil
}

// AddDomainRoleRpl_DataMultiError is an error wrapping multiple validation
// errors returned by AddDomainRoleRpl_Data.ValidateAll() if the designated
// constraints aren't met.
type AddDomainRoleRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddDomainRoleRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddDomainRoleRpl_DataMultiError) AllErrors() []error { return m }

// AddDomainRoleRpl_DataValidationError is the validation error returned by
// AddDomainRoleRpl_Data.Validate if the designated constraints aren't met.
type AddDomainRoleRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddDomainRoleRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddDomainRoleRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddDomainRoleRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddDomainRoleRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddDomainRoleRpl_DataValidationError) ErrorName() string {
	return "AddDomainRoleRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e AddDomainRoleRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddDomainRoleRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddDomainRoleRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddDomainRoleRpl_DataValidationError{}

// Validate checks the field values on UpdateDomainRoleRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDomainRoleRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDomainRoleRpl_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDomainRoleRpl_DataMultiError, or nil if none found.
func (m *UpdateDomainRoleRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDomainRoleRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UpdateTime

	// no validation rules for Name

	// no validation rules for Domain

	if len(errors) > 0 {
		return UpdateDomainRoleRpl_DataMultiError(errors)
	}

	return nil
}

// UpdateDomainRoleRpl_DataMultiError is an error wrapping multiple validation
// errors returned by UpdateDomainRoleRpl_Data.ValidateAll() if the designated
// constraints aren't met.
type UpdateDomainRoleRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDomainRoleRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDomainRoleRpl_DataMultiError) AllErrors() []error { return m }

// UpdateDomainRoleRpl_DataValidationError is the validation error returned by
// UpdateDomainRoleRpl_Data.Validate if the designated constraints aren't met.
type UpdateDomainRoleRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDomainRoleRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDomainRoleRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDomainRoleRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDomainRoleRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDomainRoleRpl_DataValidationError) ErrorName() string {
	return "UpdateDomainRoleRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDomainRoleRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDomainRoleRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDomainRoleRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDomainRoleRpl_DataValidationError{}

// Validate checks the field values on DeleteDomainRoleRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDomainRoleRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDomainRoleRpl_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDomainRoleRpl_DataMultiError, or nil if none found.
func (m *DeleteDomainRoleRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDomainRoleRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeleteTime

	if len(errors) > 0 {
		return DeleteDomainRoleRpl_DataMultiError(errors)
	}

	return nil
}

// DeleteDomainRoleRpl_DataMultiError is an error wrapping multiple validation
// errors returned by DeleteDomainRoleRpl_Data.ValidateAll() if the designated
// constraints aren't met.
type DeleteDomainRoleRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDomainRoleRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDomainRoleRpl_DataMultiError) AllErrors() []error { return m }

// DeleteDomainRoleRpl_DataValidationError is the validation error returned by
// DeleteDomainRoleRpl_Data.Validate if the designated constraints aren't met.
type DeleteDomainRoleRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDomainRoleRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDomainRoleRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDomainRoleRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDomainRoleRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDomainRoleRpl_DataValidationError) ErrorName() string {
	return "DeleteDomainRoleRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDomainRoleRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDomainRoleRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDomainRoleRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDomainRoleRpl_DataValidationError{}

// Validate checks the field values on GetAllDomainsRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllDomainsRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllDomainsRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllDomainsRpl_DataMultiError, or nil if none found.
func (m *GetAllDomainsRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllDomainsRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Domain

	// no validation rules for Name

	if len(errors) > 0 {
		return GetAllDomainsRpl_DataMultiError(errors)
	}

	return nil
}

// GetAllDomainsRpl_DataMultiError is an error wrapping multiple validation
// errors returned by GetAllDomainsRpl_Data.ValidateAll() if the designated
// constraints aren't met.
type GetAllDomainsRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllDomainsRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllDomainsRpl_DataMultiError) AllErrors() []error { return m }

// GetAllDomainsRpl_DataValidationError is the validation error returned by
// GetAllDomainsRpl_Data.Validate if the designated constraints aren't met.
type GetAllDomainsRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllDomainsRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllDomainsRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllDomainsRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllDomainsRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllDomainsRpl_DataValidationError) ErrorName() string {
	return "GetAllDomainsRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllDomainsRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllDomainsRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllDomainsRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllDomainsRpl_DataValidationError{}

// Validate checks the field values on GetDomainRolesRpl_Role with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDomainRolesRpl_Role) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDomainRolesRpl_Role with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDomainRolesRpl_RoleMultiError, or nil if none found.
func (m *GetDomainRolesRpl_Role) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDomainRolesRpl_Role) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Domain

	if len(errors) > 0 {
		return GetDomainRolesRpl_RoleMultiError(errors)
	}

	return nil
}

// GetDomainRolesRpl_RoleMultiError is an error wrapping multiple validation
// errors returned by GetDomainRolesRpl_Role.ValidateAll() if the designated
// constraints aren't met.
type GetDomainRolesRpl_RoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDomainRolesRpl_RoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDomainRolesRpl_RoleMultiError) AllErrors() []error { return m }

// GetDomainRolesRpl_RoleValidationError is the validation error returned by
// GetDomainRolesRpl_Role.Validate if the designated constraints aren't met.
type GetDomainRolesRpl_RoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDomainRolesRpl_RoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDomainRolesRpl_RoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDomainRolesRpl_RoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDomainRolesRpl_RoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDomainRolesRpl_RoleValidationError) ErrorName() string {
	return "GetDomainRolesRpl_RoleValidationError"
}

// Error satisfies the builtin error interface
func (e GetDomainRolesRpl_RoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDomainRolesRpl_Role.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDomainRolesRpl_RoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDomainRolesRpl_RoleValidationError{}

// Validate checks the field values on GetDomainRolesRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDomainRolesRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDomainRolesRpl_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDomainRolesRpl_DataMultiError, or nil if none found.
func (m *GetDomainRolesRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDomainRolesRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRoles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDomainRolesRpl_DataValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDomainRolesRpl_DataValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDomainRolesRpl_DataValidationError{
					field:  fmt.Sprintf("Roles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetDomainRolesRpl_DataMultiError(errors)
	}

	return nil
}

// GetDomainRolesRpl_DataMultiError is an error wrapping multiple validation
// errors returned by GetDomainRolesRpl_Data.ValidateAll() if the designated
// constraints aren't met.
type GetDomainRolesRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDomainRolesRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDomainRolesRpl_DataMultiError) AllErrors() []error { return m }

// GetDomainRolesRpl_DataValidationError is the validation error returned by
// GetDomainRolesRpl_Data.Validate if the designated constraints aren't met.
type GetDomainRolesRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDomainRolesRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDomainRolesRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDomainRolesRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDomainRolesRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDomainRolesRpl_DataValidationError) ErrorName() string {
	return "GetDomainRolesRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e GetDomainRolesRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDomainRolesRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDomainRolesRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDomainRolesRpl_DataValidationError{}

// Validate checks the field values on GetSubsInDomainRoleRpl_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubsInDomainRoleRpl_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubsInDomainRoleRpl_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubsInDomainRoleRpl_DataMultiError, or nil if none found.
func (m *GetSubsInDomainRoleRpl_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubsInDomainRoleRpl_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return GetSubsInDomainRoleRpl_DataMultiError(errors)
	}

	return nil
}

// GetSubsInDomainRoleRpl_DataMultiError is an error wrapping multiple
// validation errors returned by GetSubsInDomainRoleRpl_Data.ValidateAll() if
// the designated constraints aren't met.
type GetSubsInDomainRoleRpl_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubsInDomainRoleRpl_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubsInDomainRoleRpl_DataMultiError) AllErrors() []error { return m }

// GetSubsInDomainRoleRpl_DataValidationError is the validation error returned
// by GetSubsInDomainRoleRpl_Data.Validate if the designated constraints
// aren't met.
type GetSubsInDomainRoleRpl_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubsInDomainRoleRpl_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubsInDomainRoleRpl_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubsInDomainRoleRpl_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubsInDomainRoleRpl_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubsInDomainRoleRpl_DataValidationError) ErrorName() string {
	return "GetSubsInDomainRoleRpl_DataValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubsInDomainRoleRpl_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubsInDomainRoleRpl_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubsInDomainRoleRpl_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubsInDomainRoleRpl_DataValidationError{}
