// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 内部错误
func IsInternalErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == DomainRoleError_INTERNAL_ERR.String() && e.Code == 500
}

// 内部错误
func ErrorInternalErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, DomainRoleError_INTERNAL_ERR.String(), fmt.Sprintf(format, args...))
}

// 域角色不存在
func IsDomainRoleNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == DomainRoleError_DOMAIN_ROLE_NOT_FOUND.String() && e.Code == 404
}

// 域角色不存在
func ErrorDomainRoleNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, DomainRoleError_DOMAIN_ROLE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 参数错误
func IsInvalidArgs(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == DomainRoleError_INVALID_ARGS.String() && e.Code == 400
}

// 参数错误
func ErrorInvalidArgs(format string, args ...interface{}) *errors.Error {
	return errors.New(400, DomainRoleError_INVALID_ARGS.String(), fmt.Sprintf(format, args...))
}

// 域角色已存在
func IsDomainRoleExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == DomainRoleError_DOMAIN_ROLE_EXIST.String() && e.Code == 409
}

// 域角色已存在
func ErrorDomainRoleExist(format string, args ...interface{}) *errors.Error {
	return errors.New(409, DomainRoleError_DOMAIN_ROLE_EXIST.String(), fmt.Sprintf(format, args...))
}
