// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 内部错误
func IsInternalErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserError_INTERNAL_ERR.String() && e.Code == 500
}

// 内部错误
func ErrorInternalErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserError_INTERNAL_ERR.String(), fmt.Sprintf(format, args...))
}

// 用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserError_USER_NOT_FOUND.String() && e.Code == 404
}

// 用户不存在
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserError_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 参数确实
func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserError_CONTENT_MISSING.String() && e.Code == 400
}

// 参数确实
func ErrorContentMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserError_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

// 用户已存在
func IsUserExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserError_USER_EXIST.String() && e.Code == 409
}

// 用户已存在
func ErrorUserExist(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserError_USER_EXIST.String(), fmt.Sprintf(format, args...))
}
