server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  jwt:
    signing_key: d5cfc646-3692-4c98-98b3-ca7b8553d289
    expires_time: 604800
    buffer_time: 86400
    issuer: easyCasbin
data:
  database:
    driver: mysql
    source: dbadmin:hE4sqSfuCQeXEXwz@tcp(rm-3nsc58907o3epw2me.mysql.rds.aliyuncs.com:3306)/easyBigdata?charset=utf8mb4&parseTime=True&loc=Local
    db_name: easyBigdata
  redis:
    addr: redis://:IyY1NA3Zre76542M@r-3ns20c32d1acd834.redis.rds.aliyuncs.com:6379/4
    read_timeout: 0.2s
    write_timeout: 0.2s
consul:
  address: 192.168.1.3:8500
  scheme: http
trace:
  endpoint: http://127.0.0.1:14268/api/traces
log:
  level: info
  prefix: [easyCasbin]
  format: json
  director: /Users/zhouzhiyong/Desktop/easy-bigdata/easyCasbin/logs
  encode_level: LowercaseLevelEncoder
  stacktrace_key: stacktrace
  max_age: 30
  show_line: true
  log_in_console: true
